title = "Tia N. List - Threat Intelligence Briefings"
baseURL = 'https://zarguell.github.io/tia-n-list/'
languageCode = 'en-us'
defaultContentLanguage = "en"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
theme = "hugo-blog-awesome"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

# English language configuration
[Languages.en]
  languageName = "English"
  languageCode = "en"
  contentDir = "content"
  weight = 1

  [Languages.en.menu]
    [[Languages.en.menu.main]]
      pageRef = "/"
      name = 'Home'
      url = '/'
      weight = 10
    [[Languages.en.menu.main]]
      pageRef = "posts"
      name = 'Briefings'
      url = '/posts/'
      weight = 20
    [[Languages.en.menu.main]]
      pageRef = "tags"
      name = 'Tags'
      url = '/tags/'
      weight = 30
    [[Languages.en.menu.main]]
      name = 'RSS'
      url = '/index.xml'
      weight = 40

[Languages.en.params]
  sitename = "Tia N. List - Threat Intelligence Briefings"
  defaultColor = "auto"
  description = "Daily cybersecurity threat intelligence briefings and analysis"
  mainSections = ['posts']
  toc = true
  tocOpen = false
  goToTop = true
  dateFormat = "January 2, 2006"
  rssFeedDescription = "summary"

  [Languages.en.params.author]
    avatar = "" # No avatar image
    intro = "Daily Threat Intelligence Briefings"
    name = "Tia N. List"
    description = "Daily cybersecurity threat intelligence briefings and analysis for security professionals."

# Social media configuration
[[Languages.en.params.social]]
  name = "RSS"
  url = "/index.xml"
  icon = "rss"

[[Languages.en.params.social]]
  name = "GitHub"
  url = "https://github.com/zarguell/tia-n-list"
  icon = "github"

# Site-wide parameters
[params]
  # Enable search functionality
  search = true

  # Custom CSS
  customCSS = ["css/custom.css"]