baseURL: 'https://zarguell.github.io/tia-n-list/'
languageCode: 'en-us'
title: 'Tia N. List - Threat Intelligence Briefings'

# Site configuration
params:
  author: 'Tia N. List'
  description: 'Daily cybersecurity threat intelligence briefings and analysis'
  keywords: ['cybersecurity', 'threat intelligence', 'security', 'vulnerabilities', 'malware']

  # Navigation
  nav:
    - title: "Home"
      url: "/"
    - title: "Briefings"
      url: "/posts/"
    - title: "About"
      url: "/about/"

# Build settings
markup:
  goldmark:
    renderer:
      unsafe: true  # Allow HTML in markdown

# Taxonomies
taxonomies:
  tag: tags
  category: categories

# Output formats
outputs:
  home:
    - HTML
    - RSS
  page:
    - HTML
  section:
    - HTML
    - RSS

# Menu system
menu:
  main:
    - name: Home
      url: /
      weight: 10
    - name: Briefings
      url: /posts/
      weight: 20
    - name: Tags
      url: /tags/
      weight: 30