#!/usr/bin/env python3
"""Tia N. List — IOC extraction & feeds (tier 2).

Deterministic extraction of observables from our OWN curated coverage (never a
mirror of third-party feeds). Precision over recall: private/placeholder/outlet
domains and non-routable IPs are excluded. Confidence: corroborated = the
observable appears in >= 2 independent stories; reported = single source.
Status lifecycle: active (fresh within TTL) / expired (last seen older than TTL)
/ revoked (a takedown signal appears in the same event as the observable).

Outputs: JSON index, CSV, TXT, STIX 2.1 bundle — generated by the SSG.
"""
import ipaddress
import json
import os
import re
import uuid
from datetime import datetime, timezone

TTL_DAYS = 30

IP_RE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
DOMAIN_RE = re.compile(r"\b(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}\b", re.I)
SHA256_RE = re.compile(r"\b[0-9a-fA-F]{64}\b")

# reserved/placeholder domains that are never IOCs
RESERVED_TLDS = {"example", "test", "invalid", "local", "localhost", "internal",
                 "onion", "lan", "home"}
PLACEHOLDER_DOMAINS = {"example.com", "example.org", "example.net", "domain.com",
                       "yourdomain.com", "acme.com", "test.com", "foo.com", "bar.com",
                       "xyz.com", "sample.com", "target.com", "victim.com",
                       "attacker.com", "evil.com", "malicious.com", "legit.com",
                       "fake.com", "demo.com", "mydomain.com", "sub.example.net",
                       "google.com", "microsoft.com", "apple.com", "amazon.com",
                       "facebook.com", "twitter.com", "wikipedia.org", "github.com"}
# our own outlet set — source hosts, never IOCs
OUTLET_DOMAINS = {"securityweek.com", "thehackernews.com", "bleepingcomputer.com",
                  "theregister.com", "gbhackers.com", "malware.news", "darkreading.com",
                  "cyberscoop.com", "reuters.com", "krebsonsecurity.com", "wired.com",
                  "arstechnica.com", "apnews.com", "bbc.com", "bloomberg.com",
                  "nvd.nist.gov", "cisa.gov", "cert.pl", "recordedfuture.com",
                  "thedfirreport.com", "sofx.com", "ipurple.team", "cyberpress.org",
                  "tenable.com", "microsoft.com", "bleepingcomputer.com", "thehackernews.com"}

# takedown signals: a same-event match flips the IOC to revoked
TAKEDOWN_SIGNALS = ["sinkhol", "taken down", "seized", "dismantled", "revoked",
                    "infrastructure takedown", "shut down", "blocked by", "deleted by"]

_TYPE_ORDER = {"ipv4": 0, "domain": 1, "sha256": 2}


def _is_private_ip(s):
    try:
        ip = ipaddress.ip_address(s)
    except ValueError:
        return True
    return not ip.is_global


def _is_placeholder_domain(d):
    low = d.lower()
    tld = low.rsplit(".", 1)[-1]
    return tld in RESERVED_TLDS or low in PLACEHOLDER_DOMAINS or low in OUTLET_DOMAINS


def extract_from_text(text):
    """Return {value: type} observables found in article text, precision-filtered."""
    out = {}
    if not text:
        return out
    for m in IP_RE.finditer(text):
        ip = m.group(0)
        if not _is_private_ip(ip):
            out[ip] = "ipv4"
    for m in DOMAIN_RE.finditer(text):
        d = m.group(0).rstrip(".").lower()
        if not _is_placeholder_domain(d) and len(d) > 3:
            out[d] = "domain"
    for m in SHA256_RE.finditer(text):
        h = m.group(0).lower()
        if len(set(h)) > 2:                    # not an all-same-char placeholder
            out[h] = "sha256"
    return out


def build_index(stories, events):
    """Aggregate observables across all stories into IOC records."""
    iocs = {}
    for story in stories:
        sid = story["id"]
        for ref in story.get("events", []):
            e = events.get(ref["event_id"])
            if not e:
                continue
            md = e.get("content_md", "")
            found = extract_from_text(md)
            if not found:
                continue
            has_takedown = any(sig in md.lower() for sig in TAKEDOWN_SIGNALS)
            date = (e.get("published_at") or "")[:10]
            for value, itype in found.items():
                rec = iocs.setdefault((itype, value), {
                    "value": value, "type": itype, "first_seen": date,
                    "last_seen": date, "stories": [], "sources": [],
                })
                if date and date < rec["first_seen"]:
                    rec["first_seen"] = date
                if date and date > rec["last_seen"]:
                    rec["last_seen"] = date
                if sid not in rec["stories"]:
                    rec["stories"].append(sid)
                if e.get("url") and e["url"] not in rec["sources"]:
                    rec["sources"].append(e["url"])
                if has_takedown:
                    rec["_takedown"] = True
    now = datetime.now(timezone.utc)
    out = []
    for (itype, value), rec in iocs.items():
        last = datetime.fromisoformat((rec["last_seen"] or "2000-01-01") + "T00:00:00Z")
        age_days = (now - last).total_seconds() / 86400
        if rec.get("_takedown"):
            status = "revoked"
        elif age_days > TTL_DAYS:
            status = "expired"
        else:
            status = "active"
        confidence = "corroborated" if len(rec["stories"]) >= 2 else "reported"
        out.append({
            "value": rec["value"], "type": rec["type"],
            "first_seen": rec["first_seen"], "last_seen": rec["last_seen"],
            "status": status, "confidence": confidence,
            "n_sources": len(rec["stories"]), "stories": rec["stories"],
            "sources": rec["sources"],
        })
    out.sort(key=lambda i: (_TYPE_ORDER.get(i["type"], 9), -len(i["stories"]), i["value"]))
    return out


def to_csv(iocs):
    import csv
    from io import StringIO
    buf = StringIO()
    w = csv.writer(buf)
    w.writerow(["value", "type", "first_seen", "last_seen", "status",
                "confidence", "n_sources", "stories"])
    for i in iocs:
        w.writerow([i["value"], i["type"], i["first_seen"], i["last_seen"],
                    i["status"], i["confidence"], i["n_sources"],
                    ";".join(i["stories"])])
    return buf.getvalue()


def to_txt(iocs):
    return "\n".join(f"{i['type']}:{i['value']}" for i in iocs) + "\n"


def to_stix(iocs, base_url):
    """STIX 2.1 bundle: indicator objects with pattern, lifecycle, confidence."""
    now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    identity_id = "identity--" + str(uuid.uuid5(uuid.NAMESPACE_DNS, "tia-n-list"))
    objects = [{
        "type": "identity", "spec_version": "2.1", "id": identity_id,
        "name": "Tia N. List", "identity_class": "organization",
        "created": now, "modified": now,
    }]
    for i in iocs:
        if i["type"] == "ipv4":
            pattern = f"[ipv4-addr:value = '{i['value']}']"
        elif i["type"] == "domain":
            pattern = f"[domain-name:value = '{i['value']}']"
        else:
            pattern = f"[file:hashes.SHA-256 = '{i['value']}']"
        valid_until = (datetime.fromisoformat((i["last_seen"] or "2000-01-01") + "T00:00:00Z")
                       .astimezone(timezone.utc)).isoformat().replace("+00:00", "Z")
        objects.append({
            "type": "indicator", "spec_version": "2.1",
            "id": "indicator--" + str(uuid.uuid5(uuid.NAMESPACE_URL,
                                                 "https://tia-n-list/" + i["value"])),
            "created": i["first_seen"] + "T00:00:00Z",
            "modified": now,
            "name": f"{i['value']} ({i['type']})",
            "pattern": pattern,
            "valid_from": i["first_seen"] + "T00:00:00Z",
            "valid_until": valid_until,
            "labels": ["malicious-activity"],
            "confidence": 70 if i["confidence"] == "corroborated" else 40,
            "x_tia_status": i["status"],
            "x_tia_confidence": i["confidence"],
            "external_references": [{
                "source_name": "Tia N. List",
                "url": base_url + f"cti/iocs/?q={i['value']}",
            }],
        })
    return json.dumps({
        "type": "bundle", "id": "bundle--" + str(uuid.uuid4()),
        "spec_version": "2.1", "objects": objects,
    }, indent=1)
