# Threat Intelligence RSS Feeds Configuration
# Add your RSS/Atom feed URLs below

feeds:
  - name: "Krebs on Security"
    url: "https://krebsonsecurity.com/feed/"

  - name: "Schneier on Security"
    url: "https://www.schneier.com/feed/atom/"

  # - name: "The Hacker News"
  #   url: "https://thehackernews.com/feeds/posts/default"

  # - name: "Dark Reading"
  #   url: "https://www.darkreading.com/rss.xml"

  - name: "Threatpost"
    url: "https://threatpost.com/feed/"

  - name: "Bleeping Computer"
    url: "https://www.bleepingcomputer.com/feed/"

  - name: "CyberScoop"
    url: "https://www.cyberscoop.com/feed/"

  - name: "SecurityWeek"
    url: "https://www.securityweek.com/rss.xml"

  - name: "Infosecurity Magazine"
    url: "https://www.infosecurity-magazine.com/rss/news/"
  
  - name: "The Daily Swig"
    url: "https://portswigger.net/daily-swig/rss"

  - name: "ZDNet Security"
    url: "https://www.zdnet.com/topic/security/rss.xml"
  
  - name: "Security Engineering Notebook"
    url: "https://www.securityengineering.dev/rss/"
  
  - name: "Google Security Blog"
    url: "https://security.googleblog.com/feeds/posts/default"
  
  - name: "Microsoft Security Blog"
    url: "https://www.microsoft.com/security/blog/feed/"
  
  - name: "LuemmelSec"
    url: "https://luemmelsec.github.io/feed"
  
  - name: "Kapiche Engineering Blog"
    url: "https://engineering.kapiche.com/feed.xml"
  
  - name: "Embee Research"
    url: "https://embee-research.ghost.io/rss/"
  
  - name: "Cyber Defence News for Blue & Purple Teams"
    url: "https://bluepurple.binaryfirefly.com/feed"
  
  - name: "erev0s.com personal blog page"
    url: "https://erev0s.com/rss/"

  - name: "BananaMafia"
    url: "https://bananamafia.dev/index.xml"
  
  - name: "0xacb"
    url: "https://0xacb.com/feed.xml"
  
  - name: "dirkjanm.io"
    url: "https://dirkjanm.io/feed"

  - name: "Koen Van Impe – vanimpe.eu"
    url: "https://www.vanimpe.eu/feed/"
  
  - name: "Mayfly"
    url: "https://mayfly277.github.io/feed"
  
  - name: "MDSec"
    url: "https://www.mdsec.co.uk/feed/"
  
  - name: "Al Stacilauskas"
    url: "https://alstacilauskas.blogspot.com/rss.xml"
  
  - name: "Recon Main Blog"
    url: "https://blog.reconinfosec.com/rss.xml"

  - name: "JUMPSEC LABS"
    url: "https://labs.jumpsec.com/feed/"
  
  - name: "The AppSec and Startup focused blog"
    url: "https://kerr.ventures/feed/"

  - name: "Be4Sec"
    url: "https://be4sec.com/feed/"
  
  - name: "DoublePulsar - Medium"
    url: "https://doublepulsar.com/feed"
  
  - name: "Orange Cyberdefense"
    url: "https://sensepost.com/rss.xml"
  
  - name: "CyberFOX"
    url: "https://www.cyberfox.com/feed/"
  
  - name: "Cloud Native Security - Palo Alto Networks Blog"
    url: "https://www.paloaltonetworks.com/blog/prisma-cloud/feed/"
  
  - name: "Qualys Security Blog"
    url: "https://blog.qualys.com/feed/"