# deadlock-ransomware-uses-blockchain-to-resist-infrastructure-tak — KQL variant (derived from deadlock-ransomware-uses-blockchain-to-resist-infrastructure-tak.sigma via sigma convert)
# source-sha256: b9acc849e6a8f490cd1514eddacd4d682f5e549829374dc2d25a4ad801d35816 v1
TargetFilename endswith ".dlock" or (TargetFilename contains "HOW_RECOVER." and TargetFilename endswith ".txt") or (TargetFilename contains "RECOVERY_CHAT." and TargetFilename endswith ".html")

(DestinationHostname endswith "deadlock.liveblog365.com" or DestinationHostname endswith "dlock.liveblog365.com" or DestinationHostname endswith "deadlockblog.great-site.net" or DestinationHostname endswith "deadlockblog.medianewsonline.com") or DestinationHostname contains "deadblogdbdu5wprek7wa2o4ce7rnt6u6ntqeud3hzjjcveosgpsqqqd"
