name: Daily Threat Intelligence Briefing

on:
  schedule:
    # Run daily at 6:00 AM EST (11:00 AM UTC)
    - cron: '0 11 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  daily-intelligence:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache Hugo
      uses: actions/cache@v3
      with:
        path: /tmp/hugo
        key: ${{ runner.os }}-hugo-${{ hashFiles('**/hugo/versions.conf') }}
        restore-keys: |
          ${{ runner.os }}-hugo-

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Create data directory
      run: |
        mkdir -p data

    - name: Run JSON RSS Feed Ingestion
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LLM_PROVIDER: ${{ vars.LLM_PROVIDER || 'openrouter' }}
        OPENROUTER_FILTERING_MODEL: ${{ vars.OPENROUTER_FILTERING_MODEL || 'meta-llama/llama-3.3-8b-instruct:free' }}
        OPENROUTER_ANALYSIS_MODEL: ${{ vars.OPENROUTER_ANALYSIS_MODEL || 'openai/gpt-oss-20b:free' }}
      run: |
        echo "🔄 Starting JSON-based RSS feed ingestion..."
        PYTHONPATH=. python -m src.json_ingestion
        echo "✅ JSON RSS ingestion completed"
        echo "📊 System statistics:"
        PYTHONPATH=. python -c "from src.json_storage import JSONStorage; print(JSONStorage().get_statistics())"

    - name: Enhance Article Content
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LLM_PROVIDER: ${{ vars.LLM_PROVIDER || 'openrouter' }}
        OPENROUTER_FILTERING_MODEL: ${{ vars.OPENROUTER_FILTERING_MODEL || 'meta-llama/llama-3.3-8b-instruct:free' }}
        OPENROUTER_ANALYSIS_MODEL: ${{ vars.OPENROUTER_ANALYSIS_MODEL || 'openai/gpt-oss-20b:free' }}
      run: |
        echo "📰 Enhancing article content with full web scraping..."
        PYTHONPATH=. python scripts/enhance_content_json.py

    - name: Run JSON LLM Processing
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LLM_PROVIDER: ${{ vars.LLM_PROVIDER || 'openrouter' }}
        OPENROUTER_FILTERING_MODEL: ${{ vars.OPENROUTER_FILTERING_MODEL || 'meta-llama/llama-3.3-8b-instruct:free' }}
        OPENROUTER_ANALYSIS_MODEL: ${{ vars.OPENROUTER_ANALYSIS_MODEL || 'openai/gpt-oss-20b:free' }}
      run: |
        echo "🧠 Starting JSON-based LLM processing..."
        echo "Using LLM provider: ${LLM_PROVIDER:-openrouter}"
        echo "📊 Processing articles with AI analysis and IOC extraction"

        # Run JSON-based processing
        PYTHONPATH=. python -m src.json_processing

    - name: Generate JSON Blog Post
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LLM_PROVIDER: ${{ vars.LLM_PROVIDER || 'openrouter' }}
        OPENROUTER_FILTERING_MODEL: ${{ vars.OPENROUTER_FILTERING_MODEL || 'meta-llama/llama-3.3-8b-instruct:free' }}
        OPENROUTER_ANALYSIS_MODEL: ${{ vars.OPENROUTER_ANALYSIS_MODEL || 'openai/gpt-oss-20b:free' }}
      run: |
        echo "📝 Generating JSON-based blog post..."
        echo "Using LLM provider: ${LLM_PROVIDER:-openrouter}"
        PYTHONPATH=. python scripts/generate_blog_json.py

    - name: Commit JSON Data and Generated Content
      run: |
        echo "💾 Committing JSON data and generated content to git..."

        # Configure git user
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Add all JSON data and generated content
        git add data/
        git add hugo/content/posts/

        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No new content to commit"
        else
          # Commit with detailed message
          DATE=$(date +%Y-%m-%d)
          git commit -m "Daily threat intelligence processing - $DATE - 🤖 Generated with Claude Code"
          echo "✅ Committed JSON data and generated content"
        fi

    - name: Build Hugo Site
      env:
        HUGO_BASEURL: ${{ steps.site-url.outputs.url || 'https://yourusername.github.io/tia-n-list/' }}
      run: |
        echo "🏗️  Building Hugo site..."
        echo "🔗 Using baseURL: ${HUGO_BASEURL}"

        # Update baseURL in config if needed
        if [ "$HUGO_BASEURL" != "https://yourusername.github.io/tia-n-list/" ]; then
          sed -i.bak "s|baseURL: 'https://yourusername.github.io/tia-n-list/'|baseURL: '$HUGO_BASEURL'|g" hugo/config.yaml
        fi

        hugo -s hugo/ --minify
        echo "✅ Hugo site built successfully"

    - name: Get Site URL
      id: site-url
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_OUTPUT
        else
          echo "url=https://yourusername.github.io/tia-n-list/" >> $GITHUB_OUTPUT
        fi

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "📊 Changes detected, preparing to commit..."
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "ℹ️  No changes to commit"
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        echo "📝 Committing daily threat intelligence update..."
        git add .
        git status

        # Get current date for commit message
        DATE=$(date +'%Y-%m-%d')
        TIME=$(date +'%H:%M:%S')

        git commit -m "🛡️ Daily Threat Intelligence Briefing - $DATE

        🤖 Generated with [Claude Code](https://claude.com/claude-code)

        Co-Authored-By: Claude <noreply@anthropic.com>"

        echo "🚀 Pushing changes to repository..."
        git push

    - name: Summary of changes
      run: |
        echo "## 🛡️ Daily Threat Intelligence Briefing Summary" >> $GITHUB_STEP_SUMMARY
        echo "**Date:** $(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        # Check if blog post was generated
        if ls hugo/content/posts/*-daily-summary.md 1> /dev/null 2>&1; then
          echo "✅ **Blog Post Generated:** Successfully created daily threat intelligence briefing" >> $GITHUB_STEP_SUMMARY
          LATEST_POST=$(ls -t hugo/content/posts/*-daily-summary.md | head -1)
          if [ -f "$LATEST_POST" ]; then
            WORD_COUNT=$(wc -w < "$LATEST_POST")
            echo "- **Word Count:** $WORD_COUNT words" >> $GITHUB_STEP_SUMMARY
            echo "- **File:** $(basename $LATEST_POST)" >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "⚠️ **Blog Post:** No new daily briefing generated" >> $GITHUB_STEP_SUMMARY
        fi

        echo "" >> $GITHUB_STEP_SUMMARY

        # Check JSON storage status
        if [ -d "data" ]; then
          ARTICLE_COUNT=$(find data/articles -name "*.json" -type f | wc -l)
          PROCESSED_COUNT=$(find data/articles -name "*.json" -type f -exec grep -l '"status": "processed"' {} \; | wc -l)
          echo "📊 **JSON Storage Statistics:**" >> $GITHUB_STEP_SUMMARY
          echo "- **Total Articles:** $ARTICLE_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- **Processed Articles:** $PROCESSED_COUNT" >> $GITHUB_STEP_SUMMARY
        fi

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "🔗 **View Site:** Check the [Hugo site](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/) for the latest briefing." >> $GITHUB_STEP_SUMMARY

  # Optional: Build and deploy to GitHub Pages
  build-and-deploy:
    needs: daily-intelligence
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo site
      run: hugo -s hugo/ --minify

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./hugo/public

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
